import {test} from 'node:test';import assert from 'node:assert/strict';
import {device,ApiError,type Identity} from '../lib/auth';import {communityApi} from '../lib/community-api';
process.env.STAFF_SESSION_SECRET='test-only-session-secret-longer-than-32-characters';
const user:Identity={id:'player',email:'Player View',role:'player',player:null,admin:false};
const raw={Player_Roster:[{A:'Player Name'},{A:'Player A'},{A:'Player B'}],Player_Data:[{C:'Player Name'}],Games:[{E:'Opponent'}]};
const token=device(new Request('https://swish.example/api/auth/me')).token;
const req=(body:any)=>new Request('https://swish.example/api/award-votes',{method:'POST',headers:{cookie:'swish_device='+token,'Content-Type':'application/json'},body:JSON.stringify(body)});
function db(){const votes=new Map<string,any>();const DB:any={prepare(sql:string){let args:any[]=[];return {bind(...a:any[]){args=a;return this},async first(){if(sql.includes('FROM dataset'))return {raw:JSON.stringify(raw),updated:new Date().toISOString()};return null},async run(){if(sql.includes('INSERT INTO award_votes')){const key=JSON.stringify([args[1],args[3],args[4]]);votes.set(key,{player:args[2],reason:args[5]});}return {meta:{changes:1}}},async all(){return {results:[]}}}}};return {DB,votes};}
test('commendations replace only this browser award/season vote and do not award trophies',async()=>{const {DB,votes}=db();for(const player of ['Player A','Player B']){const r=await communityApi(req({player,title:'Teammate of the Year',season:'2026',reason:'Helps everyone'}),'award-votes',user,DB);assert.equal(r?.status,200);}assert.equal(votes.size,1);assert.equal([...votes.values()][0].player,'Player B');await communityApi(req({player:'Player A',title:'Most Improved Player',season:'2026'}),'award-votes',user,DB);assert.equal(votes.size,2);});
test('votes require a roster player, season, allowed category and stable signed device',async()=>{const {DB}=db();const valid={player:'Player A',title:'Teammate of the Year',season:'2026'};for(const b of [{...valid,player:'Unknown'},{...valid,title:'Game MVP'},{...valid,season:'whenever'},{...valid,reason:'x'.repeat(601)}])await assert.rejects(communityApi(req(b),'award-votes',user,DB),ApiError);const r=new Request('https://swish.example/api/award-votes',{method:'POST',body:JSON.stringify(valid)});await assert.rejects(communityApi(r,'award-votes',user,DB),(e:any)=>e.status===409);});
test('direct community handler also protects attendance and official awards',async()=>{const {DB}=db();for(const path of ['check-ins','awards','awards/delete','notes','lineup-stints'])await assert.rejects(communityApi(req({}),path,user,DB),(e:any)=>e.status===403);});
