import {test} from 'node:test';import assert from 'node:assert/strict';import {names,videoLink,validateStint,communityApi} from '../lib/community-api';import {ApiError,type Identity} from '../lib/auth';
const coach:Identity={id:'shared-staff',email:'SWISH staff',role:'coach',player:null,admin:true};
const request=(path:string,body:any)=>new Request('https://swish.example/api/'+path,{method:'POST',body:JSON.stringify(body)});
test('attendance accepts simple names and deduplicates case-insensitively',()=>{assert.deepEqual(names('Alice\nBob, alice\n Carol'),['alice','Bob','Carol']);assert.throws(()=>names('a'.repeat(101)),ApiError)});
test('video URLs use an exact provider allowlist and canonical embed URLs',()=>{assert.equal(videoLink('https://youtu.be/dQw4w9WgXcQ?t=10').embed,'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ');assert.equal(videoLink('https://www.instagram.com/reel/ABC_123/').embed,'https://www.instagram.com/reel/ABC_123/embed/');for(const u of ['javascript:alert(1)','https://youtube.com.evil.test/watch?v=dQw4w9WgXcQ','https://evil.test/movie','not a url','http://youtu.be/dQw4w9WgXcQ','https://www.instagram.com/accounts/login/'])assert.throws(()=>videoLink(u),ApiError)});
const stint={id:'stint1',game:'game1',players:['A','B','C','D','E'],period:1,startClock:600,endClock:500,startFor:0,startAgainst:0,endFor:4,endAgainst:2,possFor:null,possAgainst:null,note:''};
test('stints require five unique names, countdown clocks and monotonic scores',()=>{assert.equal(validateStint(stint).start,600);for(const b of [{players:['A','A','C','D','E']},{endClock:601},{period:0},{startFor:5},{possFor:2},{possFor:0,possAgainst:1}])assert.throws(()=>validateStint({...stint,...b}),ApiError)});
test('attendance editing rejects stale revisions rather than overwriting another volunteer',async()=>{const DB:any={prepare(){return {bind(){return this},async run(){return {meta:{changes:0}}}}}};await assert.rejects(communityApi(request('check-ins',{id:'saved',revision:1,title:'Saturday',date:'2026-10-09',kind:'Match',names:'Alice'}),'check-ins',coach,DB),(e:any)=>e.status===409)});
test('staff-only community mutations require PIN identity',async()=>{await assert.rejects(communityApi(request('films',{url:'https://youtu.be/dQw4w9WgXcQ'}),'films',{...coach,role:'player'},{}),(e:any)=>e.status===403)});
