import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {JSDOM} from 'jsdom';
const raw={Player_Roster:[{A:'Player Name',B:'Position',C:'Shoots',D:'Status'},{A:'Player A',B:'PG',C:'Right',D:'Active'},{A:'Player B',B:'SG',D:'Active'}],Player_Data:[{C:'Player Name',D:'Date',E:'Opponent'},{C:'Player A',D:46304,E:'Rivals',I:9,J:2,K:3,L:1,M:0,O:1,V:3,W:6,Z:2,AA:4,AB:1,AC:2,AD:2,AE:2}],Games:[{C:'Date',E:'Opponent'},{A:'game1',C:46304,D:'5v5',E:'Rivals',G:9,H:8}],Shot_Data:[]};
async function setup(role:string,opts:{remembered?:string;offline?:boolean}={}){const html=readFileSync('public/hub/index.html','utf8'),dom=new JSDOM(html,{url:'https://swish.example/hub/index.html',runScripts:'outside-only',pretendToBeVisual:true}),w:any=dom.window;const errors:any[]=[],writes:any[]=[];if(opts.remembered)w.localStorage.setItem('swish-selected-player',opts.remembered);w.addEventListener('error',(e:any)=>errors.push(e.error));w.SwishAuth={user:{id:role,email:'Staff',role,player:null,admin:role!=='player'},ready:Promise.resolve()};w.SwishAuth.ready=Promise.resolve(w.SwishAuth.user);w.Response=Response;w.setInterval=()=>0;w.confirm=()=>true;w.matchMedia=()=>({matches:true});w.fetch=async(input:string,options:any)=>{if(options?.method==='POST'){writes.push({path:input,body:JSON.parse(options.body)});return Response.json({ok:true});}if(input.includes('film-room.json'))return Response.json({version:1,clips:[{id:'f1',title:'Clip <test>',url:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',category:'Skills Library',cue:'Watch the spacing'}]});if(input.includes('live-sheet'))return Response.json({raw,name:'Live Google Sheet',signature:'test',syncedAt:new Date().toISOString()});if(input.includes('check-ins')||input.includes('notes'))return Response.json([]);if(input.includes('setup'))return Response.json({database:true,googleWrite:true,staffPin:true,sessionSecret:true});if(opts.offline)return Response.json({error:'Shared saves unavailable'},{status:503});return Response.json({films:[{id:'f1',title:'Clip <test>',url:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',provider:'youtube',category:'Skills library',cue:'Watch the spacing'}],awards:[{id:'a1',player:'Player A',title:'Game MVP',season:'2026',event_key:'g1',awarded:'2026-10-09',reason:'Hustle'},{id:'a2',player:'Player A',title:'Game MVP',season:'2026',event_key:'g2',awarded:'2026-10-09',reason:'Hustle'}],predictions:[{id:'p1',player:'Player A',date:'2026-10-09',opponent:'rivals',metrics:{pts:8}}],stints:[],backendReady:true});};w.eval(['model','development','courts','app','film-library','clubhouse','live-sheet','access','game-entry','interface'].map(name=>readFileSync(`public/hub/${name}.js`,'utf8')).join('\n')+'\nwindow.testSetView=setView;');w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await new Promise(resolve=>setTimeout(resolve,40));return {dom,w,errors,writes};}
test('shared staff view boots and game drafts survive navigation',async()=>{const {dom,w,errors}=await setup('volunteer');try{assert.deepEqual(errors,[]);assert.equal(w.document.getElementById('load-status').textContent,'');w.eval("testSetView('add-game')");const rows=w.document.querySelectorAll('[data-box-name]');assert.equal(rows.length,2);assert.equal(w.document.querySelector('[data-view="lineups"]').hidden,false);const row=rows[0],box=row.querySelector('[data-played]');box.checked=true;box.dispatchEvent(new w.Event('change',{bubbles:true}));const f=w.document.getElementById('game-entry-form');f.elements.opponent.value='Rivals';f.elements.score.value='9';row.querySelector('[data-box="pts"]').value='9';f.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.document.getElementById('game-entry-gap').textContent,'0');w.eval("testSetView('progress');testSetView('add-game')");assert.equal(w.document.querySelector('[data-box="pts"]').value,'9');assert(w.document.querySelector('[data-played]').checked);}finally{dom.window.close()}});
test('public player view has predictions, embedded film, grind animations and repeat awards',async()=>{const {dom,w,errors}=await setup('player');try{assert.deepEqual(errors,[]);assert.equal(w.document.querySelector('[data-view="add-game"]').hidden,false);w.eval("testSetView('notes')");assert.equal(w.document.getElementById('notes').hidden,false);assert.equal(w.document.querySelector('[data-view="quests"]'),null);w.eval("testSetView('predictions')");assert(w.document.getElementById('prediction-list').textContent.includes('8 → 9'));w.eval("testSetView('film')");w.document.querySelector('[data-film-id]').click();assert.equal(w.document.querySelector('.film-embed').src,'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ');assert(w.document.getElementById('film-viewer').textContent.includes('Clip <test>'));w.eval("testSetView('accolades')");assert(w.document.getElementById('award-counts').textContent.includes('2×'));w.eval("testSetView('grind')");assert(w.document.querySelector('.practice-court'));w.document.getElementById('court-next').click();assert(w.document.querySelector('.court-step').textContent.includes('STEP 2'));assert(w.document.getElementById('player-level').textContent.includes('Provisional'));}finally{dom.window.close()}});
test('simple attendance form sends names without broad categories',async()=>{const {dom,w,writes}=await setup('coach');try{w.eval("testSetView('sessions')");const f=w.document.getElementById('check-form');f.elements.title.value='Saturday';f.elements.date.value='2026-10-09';f.elements.names.value='Alice\nBob';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(resolve=>setTimeout(resolve,30));assert.equal(writes[0].path,'/api/check-ins');assert.equal(writes[0].body.names,'Alice\nBob');assert.equal(writes[0].body.kind,'Volunteering session');assert.equal(writes[0].body.state,undefined);}finally{dom.window.close()}});
test('lineup aggregation uses recorded stint deltas and suppresses uncounted possessions',async()=>{const {dom,w}=await setup('coach');try{const base={game_id:'g1',players:['A','B','C','D','E'],start_clock:600,end_clock:480,start_for:10,start_against:10,end_for:16,end_against:12,poss_for:4,poss_against:4};const g=w.Development.lineups([base,{...base,players:['E','D','C','B','A'],start_clock:480,end_clock:360,start_for:16,start_against:12,end_for:18,end_against:16,poss_for:null,poss_against:null}])[0];assert.equal(g.minutes,4);assert.equal(g.plusMinus,2);assert.equal(g.per40,20);assert.equal(g.off100,null);assert.equal(g.stints,2);const counted=w.Development.lineups([base])[0];assert.equal(counted.off100,150);assert.equal(counted.def100,50);}finally{dom.window.close()}});
test('ratings keep missing values unscored; shooting uses matched records',async()=>{const {dom,w}=await setup('player');try{const s=w.Development.shooting([{fgm:2,fga:4},{fgm:10,fga:null}],'fgm','fga');assert.equal(s.rate,.5);assert.equal(s.makes,2);const p=w.Swish.build(raw).players.find((p:any)=>p.name==='Player B');assert.equal(w.Development.ratings(p).overall,null);assert.equal(w.Development.badges(p).length,0);}finally{dom.window.close()}});
test('Title Case preserves stat acronyms, player names and backend selection values',async()=>{const {dom,w}=await setup('coach');try{
  assert.equal(w.Interface.titleCase('SWISH myplayer • game MVP • 3PT • 2K • defensive activity'), 'SWISH MyPlayer • Game MVP • 3PT • 2K • Defensive Activity');
  const select=w.document.querySelector('#check-form select[name="kind"]');
  assert.equal(select.selectedOptions[0].textContent, 'Volunteering Session');
  assert.equal(select.value, 'Volunteering session');
  assert.equal(select.title, 'Volunteering Session');
  const roster=w.document.getElementById('player');
  roster.options[0].textContent='KeJie';w.Interface.format();
  assert.equal(roster.options[0].textContent, 'KeJie');
  assert(w.document.querySelector('.table-scroll').hasAttribute('tabindex'));
}finally{dom.window.close()}});

test('Clubhouse selection persists across every individual tab and refresh',async()=>{const {dom,w}=await setup('community');try{assert.equal(w.document.getElementById('home').hidden,false);const select=w.document.getElementById('home-player');select.value='Player B';select.dispatchEvent(new w.Event('change',{bubbles:true}));for(const id of ['player','prediction-player','grind-player','award-player','award-filter','note-player'])assert.equal(w.document.getElementById(id).value,'Player B',id);for(const page of ['progress','predictions','grind','accolades','notes','home']){w.eval(`testSetView('${page}')`);assert.equal(w.document.getElementById('player').value,'Player B');}assert.equal(w.localStorage.getItem('swish-selected-player'),'Player B');await w.LiveSheets.refresh(true);assert.equal(w.document.getElementById('home-player').value,'Player B');const other=w.document.getElementById('prediction-player');other.value='Player A';other.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(select.value,'Player A');}finally{dom.window.close()}});
test('Film Room device drafts support Drive, plays and validated static export without API writes',async()=>{const {dom,w,writes}=await setup('community');try{w.eval("testSetView('film')");assert.equal(w.document.querySelectorAll('[data-film-shelf]').length,4);const f=w.document.getElementById('film-form');f.elements.title.value='Our Game';f.elements.category.value='5 On 5 Plays';f.elements.url.value='https://drive.google.com/file/d/abcdefghijklmnop/view?usp=sharing';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(writes.length,0);assert.equal(w.document.querySelector('.film-embed').src,'https://drive.google.com/file/d/abcdefghijklmnop/preview');assert(f.querySelector('.form-feedback').textContent.includes('Device draft'));const exported=w.FilmLibrary.exportCatalogue();assert.equal(exported.clips.length,2);assert.equal(exported.clips[1].category,'5 On 5 Plays');assert.throws(()=>w.FilmLibrary.video('https://drive.google.com/drive/folders/abcdefghijklmnop'));assert.throws(()=>w.FilmLibrary.video('https://youtube.com.evil.example/watch?v=dQw4w9WgXcQ'));assert.throws(()=>w.FilmLibrary.importCatalogue({version:1,clips:[...exported.clips,exported.clips[0]]}));w.FilmLibrary.reset();assert.equal(w.FilmLibrary.clips().length,1);}finally{dom.window.close()}});

test('a new page restores the remembered player and published films survive a database outage',async()=>{const {dom,w,errors}=await setup('community',{remembered:'Player B',offline:true});try{assert.deepEqual(errors,[]);assert.equal(w.document.getElementById('home-player').value,'Player B');assert.equal(w.document.getElementById('player').value,'Player B');w.eval("testSetView('film')");assert.equal(w.FilmLibrary.clips().length,1);assert(w.document.querySelector('[data-film-id]'));w.document.querySelector('[data-film-id]').click();assert(w.document.querySelector('.film-embed').src.includes('youtube-nocookie.com'));assert.equal(w.document.getElementById('film-form').elements.category.options.length,4);}finally{dom.window.close()}});
test('worksheet CSV escapes formula text and quoted names',async()=>{const {dom,w}=await setup('community');try{const csv=w.GameEntry.worksheetCSV({date:'2026-10-09',opponent:'=IMPORTXML("evil")',type:'5v5',score:9,against:8,players:[{name:'A, "B"',pts:9}]});assert(csv.includes('"\'=IMPORTXML(""evil"")"'));assert(csv.includes('"A, ""B"""'));}finally{dom.window.close()}});
