import {test} from 'node:test';import assert from 'node:assert/strict';import {validateGame,gameRequests,writeGame} from '../lib/game-entry';import {ApiError} from '../lib/auth';
import {fields,prepareFields} from '../lib/sheet-fields';
const fixture=()=>({id:'018de444-6e20-4f90-923f-6748a33b91ce',date:'2026-10-09',opponent:'Rivals',type:'5v5',division:'U18',tags:['League'],score:9,against:8,players:[{name:'Player A',pts:9,reb:2,ast:3,stl:1,blk:0,to:1,twoMade:2,twoAtt:4,threeMade:1,threeAtt:2,ftm:2,fta:2}]});
test('validates score totals, makes/attempts, shot points, duplicate names and dates',()=>{validateGame(fixture());for(const change of [ {score:8}, {date:'2026-02-30'}, {players:[{...fixture().players[0],twoMade:5}]},{players:[{...fixture().players[0],pts:8}]},{players:[...fixture().players,...fixture().players]},{players:[{...fixture().players[0],ast:-1}]},{players:[{...fixture().players[0],ftm:null}]}])assert.throws(()=>validateGame({...fixture(),...change}),ApiError)});
test('unknown optional shooting stays blank',()=>{const f=fixture();const p:any=f.players[0];for(const k of ['twoMade','twoAtt','threeMade','threeAtt','ftm','fta'])p[k]=null;const r:any=gameRequests(validateGame(f),{games:1,players:2},[{A:'Player A',B:'PG'}],'hash');const cells=r[3].updateCells.rows[0].values;assert.deepEqual(cells[21],{});assert.deepEqual(cells[22],{});assert.deepEqual(cells[25],{});assert.equal(cells[8].userEnteredValue.numberValue,9)});
test('atomic batch maps real tracker columns and marker; text cannot inject formulas',()=>{const f=fixture();f.opponent='=IMPORTXML("evil")';f.players[0].name='=Player';const r:any=gameRequests(validateGame(f),{games:123,players:456},[{A:'=Player',B:'PG'}],'hash');assert.equal(r.length,5);assert.equal(r[0].insertDimension.range.startIndex,1);assert.equal(r[1].insertDimension.range.endIndex,2);const g=r[2].updateCells.rows[0].values,p=r[3].updateCells.rows[0].values;assert.equal(g[4].userEnteredValue.stringValue,f.opponent);assert.equal(g[2].userEnteredValue.numberValue,46304);assert.equal(p[2].userEnteredValue.stringValue,'=Player');assert.equal(p[21].userEnteredValue.numberValue,3);assert.equal(p[22].userEnteredValue.numberValue,6);assert.equal(p[27].userEnteredValue.numberValue,1);assert.equal(p[29].userEnteredValue.numberValue,2);assert.match(p[15].userEnteredValue.formulaValue,/V2\/W2/);assert.equal(r[4].createDeveloperMetadata.developerMetadata.metadataValue,'hash')});
function services(){let marker=false,writes=0,status:string|undefined,hash:string|undefined,failOnce=true,released=0;const client:any={async query(sql:string,v:any[]){if(sql.startsWith('SELECT * FROM game_submissions'))return {rows:status?[{status,payload_hash:hash}]:[]};if(sql.includes('INSERT INTO game_submissions')){hash=v[1];status=sql.includes("'complete'")?'complete':'pending';}return {rows:[],rowCount:1}},release(){released++}};const pool:any={async connect(){return client}};const google:any=async(path:string,body:any)=>{if(path==='/developerMetadata:search')return {matchedDeveloperMetadata:marker?[{developerMetadata:{metadataValue:hash}}]:[]};if(path.startsWith('?fields='))return {sheets:[{properties:{title:'Games',sheetId:1}},{properties:{title:'Player_Data',sheetId:2}}]};if(path===':batchUpdate'){writes++;marker=true;if(failOnce){failOnce=false;throw new ApiError('Network timeout',503)}return {}};throw Error(path)};const read:any=async()=>({Games:[{}, {C:40000,E:'Old'}],Player_Data:[{}],Player_Roster:[{}, {A:'Player A',B:'PG'}]});return {pool,google,read,stats:()=>({writes,status,released})};}
test('uncertain atomic write retries via sheet marker without duplicate insert',async()=>{const s=services(),g=validateGame(fixture());await assert.rejects(writeGame(g,'coach',s),ApiError);assert.equal(s.stats().writes,1);assert.equal(s.stats().status,'pending');await writeGame(g,'coach',s);assert.equal(s.stats().writes,1);assert.equal(s.stats().status,'complete');const r=await writeGame(g,'coach',s);assert.equal(r.alreadySaved,true);assert.equal(s.stats().released,3)});
test('submitted draft ID cannot silently change its payload',async()=>{const s=services(),g=validateGame(fixture());await assert.rejects(writeGame(g,'coach',s));await assert.rejects(writeGame({...g,against:7},'coach',s),(e:any)=>e.status===409);assert.equal(s.stats().writes,1)});
test('duplicate existing sheet game rejected before any insert',async()=>{const s=services();s.read=async()=>({Games:[{}, {C:Date.parse('2026-10-09')/86400000+25569,E:'Rivals'}],Player_Data:[{}],Player_Roster:[{}, {A:'Player A'}]});await assert.rejects(writeGame(validateGame(fixture()),'coach',s),(e:any)=>e.status===409);assert.equal(s.stats().writes,0)});
test('every new game needs a division and custom tags are validated',()=>{for(const change of [{division:''},{division:null},{tags:['League','league']},{tags:['x'.repeat(81)]}])assert.throws(()=>validateGame({...fixture(),...change}),ApiError);assert.equal(validateGame({...fixture(),division:'Girls U16'}).division,'Girls U16');});
test('game metadata and only participating player rows are included in the same atomic batch',()=>{
 const g=validateGame(fixture()),games=prepareFields([{A:'Game ID',J:'Existing Formula'}],{sheetId:1,gridProperties:{columnCount:26}},Object.values(fields).slice(0,3),9),players=prepareFields([{C:'Player Name',AN:'Staff Remark'}],{sheetId:2,gridProperties:{columnCount:40}},Object.values(fields).slice(0,3),40);
 const r:any[]=gameRequests(g,{games:1,players:2},[{A:'Player A'},{A:'Player B'}],'hash',15,{}, {games:games.columns,players:players.columns});
 assert.equal(r[3].updateCells.rows.length,1);const a=r[2].updateCells.rows[0].values,b=r[3].updateCells.rows[0].values;assert.equal(a[games.columns[fields.division]].userEnteredValue.stringValue,'U18');assert.equal(b[players.columns[fields.division]].userEnteredValue.stringValue,'U18');assert.equal(a[games.columns[fields.gameId]].userEnteredValue.stringValue,b[players.columns[fields.gameId]].userEnteredValue.stringValue);assert.deepEqual(JSON.parse(b[players.columns[fields.tags]].userEnteredValue.stringValue),['League']);
});
test('different divisions can log the same date/opponent; the same division still cannot',async()=>{
 const s=services(),serial=Date.parse('2026-10-09')/86400000+25569;s.read=async()=>({Games:[{J:fields.division},{C:serial,E:'Rivals',J:'U21'}],Player_Data:[{AO:fields.division},{D:serial,E:'Rivals',AO:'U21'}],Player_Roster:[{}, {A:'Player A'}]});
 await assert.rejects(writeGame(validateGame(fixture()),'coach',s),(e:any)=>e.status===503);assert.equal(s.stats().writes,1);
 const duplicate=services();duplicate.read=s.read;await assert.rejects(writeGame(validateGame({...fixture(),division:'U21'}),'coach',duplicate),(e:any)=>e.status===409);assert.equal(duplicate.stats().writes,0);
});

test('every player tracker input maps to its original column; remarks remain literal',()=>{
 const f:any=fixture();Object.assign(f.players[0],{position:'SF',jersey:23,minutes:18.5,plusMinus:-4,foul:3,closeMade:1,closeAtt:2,oreb:1,dreb:1,contest:5,deflect:4,passingTo:1,remarks:'=IMPORTXML("no")'});f.boxScore='https://example.com/box';f.gameEvents='https://example.com/events';
 const r:any=gameRequests(validateGame(f),{games:1,players:2},[{A:'Player A',B:'PG'}],'hash'),v=r[3].updateCells.rows[0].values,g=r[2].updateCells.rows[0].values;
 for(const [i,x] of [[1,23],[6,18.5],[7,-4],[13,3],[23,1],[24,2],[31,1],[32,1],[33,5],[34,4],[37,1],[38,1]])assert.equal(v[i as number].userEnteredValue.numberValue,x);
 assert.equal(v[0].userEnteredValue.stringValue,'SF');assert.equal(v[39].userEnteredValue.stringValue,'=IMPORTXML("no")');assert.match(v[36].userEnteredValue.formulaValue,/K2\/AL2/);assert.equal(g[9].userEnteredValue.stringValue,f.boxScore);assert.equal(g[10].userEnteredValue.stringValue,f.gameEvents);
});
test('optional fields stay unknown, direct field-goal totals work without a split, and consistency is enforced',()=>{
 const f:any=fixture();let g=validateGame(f);const v:any=gameRequests(g,{games:1,players:2},[],'h')[3];for(const i of [1,6,7,13,23,24,31,32,33,34,36,37,39])assert.deepEqual(v.updateCells.rows[0].values[i],{});
 for(const update of [{oreb:1,dreb:2},{oreb:3},{passingTo:2},{closeMade:3,closeAtt:3},{fgm:2,fga:6},{minutes:-1},{plusMinus:1.5},{closeMade:0,closeAtt:null}])assert.throws(()=>validateGame({...f,players:[{...f.players[0],...update}]}),ApiError);
 g=validateGame({...f,players:[{...f.players[0],twoMade:null,twoAtt:null,threeMade:null,threeAtt:null,fgm:3,fga:6}]});assert.equal(g.players[0].fgm,3);assert.equal(g.players[0].twoMade,null);
});
test('shot validation supports partial logs, all detail fields and rejects duplicates or totals exceeding the box score',()=>{
 const f:any=fixture();f.shots=[{name:'Player A',number:23,zone:'3PT - Left Wing',result:'Make',hand:'R',detail:'Rim-In',error:'',type:'Catch & Shoot',situation:'Transition',play:'Kick Out',contest:'Open',assisted:'Yes',assister:'Player B',quality:'Good',remarks:'=literal'}];const g=validateGame(f);assert.equal(g.shots[0].remarks,'=literal');
 for(const shots of [[...f.shots,...f.shots],[{...f.shots[0],name:'Absent'}],[{...f.shots[0],zone:''}],[{...f.shots[0],result:'Unknown'}],[{...f.shots[0],assisted:'No'}],[{...f.shots[0],hand:'Invalid'}],[...f.shots,{...f.shots[0],number:24}]])assert.throws(()=>validateGame({...f,shots}),ApiError);
});
test('game, box scores, shot rows and the retry receipt use one atomic write, including a missing shot tab',async()=>{
 const f:any=fixture();f.shots=[{name:'Player A',zone:'Paint (Non-restricted)',result:'Make',remarks:'=DoNotExecute'}];const s=services();let batches:any[]=[];const original=s.google;s.google=async(path:string,body:any)=>{if(path===':batchUpdate')batches.push(body.requests);return original(path,body)};
 await assert.rejects(writeGame(validateGame(f),'coach',s));assert.equal(batches.length,1);const batch=batches[0];assert(batch.some((r:any)=>r.addSheet?.properties.title==='Shot_Data'));const shots=batch.find((r:any)=>r.updateCells?.start.sheetId===3&&r.updateCells.start.rowIndex===1).updateCells.rows;
 assert.equal(shots.length,1);const v=shots[0].values;assert.equal(v[0].userEnteredValue.stringValue,'46304_1_1');assert.equal(v[4].userEnteredValue.stringValue,'Player A');assert.equal(v[17].userEnteredValue.stringValue,'=DoNotExecute');assert.equal(v.length,21);assert.equal(v[20].userEnteredValue.stringValue,'46304_1');
 await writeGame(validateGame(f),'coach',s);assert.equal(batches.length,1);
});

test('existing shot sheet records are retained; all eighteen shot fields and metadata map correctly',async()=>{
 const {shotHeaders}=await import('../lib/shot-entry');const f:any=fixture();f.shots=[{name:'Player A',number:113,zone:'Mid-Range - Left',result:'Make',hand:'R',detail:'Rim-In',error:'Short',type:'Pull-Up',situation:'Half-court Set',play:'Kick Out',contest:'Open',assisted:'Yes',assister:'Player A',quality:'Good',remarks:'A Note'}];const s=services();const original=s.google;s.google=async(path:string,body:any)=>path.startsWith('?fields=')?{sheets:[{properties:{title:'Games',sheetId:1}},{properties:{title:'Player_Data',sheetId:2}},{properties:{title:'Shot_Data',sheetId:9,gridProperties:{columnCount:26}}}]}:path===':batchUpdate'?((s as any).batch=body.requests,{}):original(path,body);const read=s.read;s.read=async()=>({...await read(),Shot_Data:[Object.fromEntries(shotHeaders.map((h,i)=>[String.fromCharCode(65+i),h.replace(' ','\n')])),{A:'existing-shot',E:'Player B',F:'Paint',G:'Make'}]});
 await writeGame(validateGame(f),'coach',s);const batch=(s as any).batch;assert(!batch.some((r:any)=>r.addSheet));const insert=batch.find((r:any)=>r.insertDimension?.range.sheetId===9);assert.equal(insert.insertDimension.range.startIndex,1);const v=batch.find((r:any)=>r.updateCells?.start.sheetId===9&&r.updateCells.start.rowIndex===1).updateCells.rows[0].values;
 assert.deepEqual(v.slice(4,18).map((c:any)=>c.userEnteredValue?.stringValue),['Player A','Mid-Range - Left','Make','R','Rim-In','Short','Pull-Up','Half-court Set','Kick Out','Open','Yes','Player A','Good','A Note']);assert.equal(v[3].userEnteredValue.numberValue,113);
});

test('total field goals minus threes derive twos and the spreadsheet split without duplicate input',()=>{
 const f:any=fixture();delete f.players[0].twoMade;delete f.players[0].twoAtt;Object.assign(f.players[0],{fgm:3,fga:6});const g=validateGame(f);assert.equal(g.players[0].twoMade,2);assert.equal(g.players[0].twoAtt,4);
 const requests:any=gameRequests(g,{games:1,players:2},[],'h');const row:any=requests[3].updateCells.rows[0].values;assert.equal(row[25].userEnteredValue.numberValue,2);assert.equal(row[26].userEnteredValue.numberValue,4);
 for(const change of [{fgm:0},{fga:1},{fgm:3,fga:3,threeMade:0,threeAtt:2},{twoMade:1,twoAtt:4}])assert.throws(()=>validateGame({...f,players:[{...f.players[0],...change}]}),ApiError);
 const zero=validateGame({...f,score:2,players:[{...f.players[0],pts:2,fgm:0,fga:0,threeMade:0,threeAtt:0}]});assert.equal(zero.players[0].twoMade,0);assert.equal(zero.players[0].twoAtt,0);
 const unknown=validateGame({...f,players:[{...f.players[0],threeMade:null,threeAtt:null}]});assert.equal(unknown.players[0].twoMade,null);
});
