import {test} from 'node:test';import assert from 'node:assert/strict';import {validateGame,gameRequests,writeGame} from '../lib/game-entry';import {ApiError} from '../lib/auth';
const fixture=()=>({id:'018de444-6e20-4f90-923f-6748a33b91ce',date:'2026-10-09',opponent:'Rivals',type:'5v5',score:9,against:8,players:[{name:'Player A',pts:9,reb:2,ast:3,stl:1,blk:0,to:1,twoMade:2,twoAtt:4,threeMade:1,threeAtt:2,ftm:2,fta:2}]});
test('validates score totals, makes/attempts, shot points, duplicate names and dates',()=>{validateGame(fixture());for(const change of [ {score:8}, {date:'2026-02-30'}, {players:[{...fixture().players[0],twoMade:5}]},{players:[{...fixture().players[0],pts:8}]},{players:[...fixture().players,...fixture().players]},{players:[{...fixture().players[0],ast:-1}]},{players:[{...fixture().players[0],ftm:null}]}])assert.throws(()=>validateGame({...fixture(),...change}),ApiError)});
test('unknown optional shooting stays blank',()=>{const f=fixture();const p:any=f.players[0];for(const k of ['twoMade','twoAtt','threeMade','threeAtt','ftm','fta'])p[k]=null;const r:any=gameRequests(validateGame(f),{games:1,players:2},[{A:'Player A',B:'PG'}],'hash');const cells=r[3].updateCells.rows[0].values;assert.deepEqual(cells[21],{});assert.deepEqual(cells[22],{});assert.deepEqual(cells[25],{});assert.equal(cells[8].userEnteredValue.numberValue,9)});
test('atomic batch maps real tracker columns and marker; text cannot inject formulas',()=>{const f=fixture();f.opponent='=IMPORTXML("evil")';f.players[0].name='=Player';const r:any=gameRequests(validateGame(f),{games:123,players:456},[{A:'=Player',B:'PG'}],'hash');assert.equal(r.length,5);assert.equal(r[0].insertDimension.range.startIndex,1);assert.equal(r[1].insertDimension.range.endIndex,2);const g=r[2].updateCells.rows[0].values,p=r[3].updateCells.rows[0].values;assert.equal(g[4].userEnteredValue.stringValue,f.opponent);assert.equal(g[2].userEnteredValue.numberValue,46304);assert.equal(p[2].userEnteredValue.stringValue,'=Player');assert.equal(p[21].userEnteredValue.numberValue,3);assert.equal(p[22].userEnteredValue.numberValue,6);assert.equal(p[27].userEnteredValue.numberValue,1);assert.equal(p[29].userEnteredValue.numberValue,2);assert.match(p[15].userEnteredValue.formulaValue,/V2\/W2/);assert.equal(r[4].createDeveloperMetadata.developerMetadata.metadataValue,'hash')});
function services(){let marker=false,writes=0,status:string|undefined,hash:string|undefined,failOnce=true,released=0;const client:any={async query(sql:string,v:any[]){if(sql.startsWith('SELECT * FROM game_submissions'))return {rows:status?[{status,payload_hash:hash}]:[]};if(sql.includes('INSERT INTO game_submissions')){hash=v[1];status=sql.includes("'complete'")?'complete':'pending';}return {rows:[],rowCount:1}},release(){released++}};const pool:any={async connect(){return client}};const google:any=async(path:string,body:any)=>{if(path==='/developerMetadata:search')return {matchedDeveloperMetadata:marker?[{developerMetadata:{metadataValue:hash}}]:[]};if(path.startsWith('?fields='))return {sheets:[{properties:{title:'Games',sheetId:1}},{properties:{title:'Player_Data',sheetId:2}}]};if(path===':batchUpdate'){writes++;marker=true;if(failOnce){failOnce=false;throw new ApiError('Network timeout',503)}return {}};throw Error(path)};const read:any=async()=>({Games:[{}, {C:40000,E:'Old'}],Player_Data:[{}],Player_Roster:[{}, {A:'Player A',B:'PG'}]});return {pool,google,read,stats:()=>({writes,status,released})};}
test('uncertain atomic write retries via sheet marker without duplicate insert',async()=>{const s=services(),g=validateGame(fixture());await assert.rejects(writeGame(g,'coach',s),ApiError);assert.equal(s.stats().writes,1);assert.equal(s.stats().status,'pending');await writeGame(g,'coach',s);assert.equal(s.stats().writes,1);assert.equal(s.stats().status,'complete');const r=await writeGame(g,'coach',s);assert.equal(r.alreadySaved,true);assert.equal(s.stats().released,3)});
test('submitted draft ID cannot silently change its payload',async()=>{const s=services(),g=validateGame(fixture());await assert.rejects(writeGame(g,'coach',s));await assert.rejects(writeGame({...g,against:7},'coach',s),(e:any)=>e.status===409);assert.equal(s.stats().writes,1)});
test('duplicate existing sheet game rejected before any insert',async()=>{const s=services();s.read=async()=>({Games:[{}, {C:Date.parse('2026-10-09')/86400000+25569,E:'Rivals'}],Player_Data:[{}],Player_Roster:[{}, {A:'Player A'}]});await assert.rejects(writeGame(validateGame(fixture()),'coach',s),(e:any)=>e.status===409);assert.equal(s.stats().writes,0)});
