import {test} from 'node:test';import assert from 'node:assert/strict';
import {communityApi,validateFilm,validateSuggestion,videoLink} from '../lib/community-api';import {device,ApiError,type Identity} from '../lib/auth';import {portableApi} from '../lib/portable-api';
process.env.STAFF_SESSION_SECRET='test-only-session-secret-longer-than-32-characters';
const player:Identity={id:'player',email:'Player',role:'player',player:null,admin:false},staff:Identity={...player,role:'coach',admin:true};
const token=device(new Request('https://swish.example/api/auth/me')).token;
const request=(path:string,b?:any)=>new Request('https://swish.example/api/'+path,{method:b?'POST':'GET',headers:{origin:'https://swish.example',cookie:'swish_device='+token},...(b?{body:JSON.stringify(b)}:{})});
const clip={id:'clip-receipt',title:'Spacing',category:'5 On 5 Plays',url:'https://drive.google.com/file/d/abcdefghijklm/view',cue:'Read the help.'};
function database(){const films=new Map<string,any>(),suggestions=new Map<string,any>();const DB:any={prepare(sql:string){let args:any[]=[];return {bind(...values:any[]){args=values;return this;},async first(){if(sql.includes('FROM dataset'))return {raw:JSON.stringify({Player_Roster:[{A:'Player'},{A:'A'}],Player_Data:[],Games:[],Shot_Data:[]}),updated:new Date().toISOString()};const table=sql.includes('FROM films')?films:suggestions;if(sql.includes('COUNT'))return {count:table.size};if(sql.includes('WHERE url'))return [...films.values()].find(f=>f.url===args[0]);return table.get(args[0])||null;},async all(){return {results:[...(sql.includes('FROM films')?films:suggestions).values()].map(({device_id,...row})=>row)};},async run(){if(sql.includes('INSERT INTO films')){const keys=['id','title','url','provider','category','cue','created'];films.set(args[0],Object.fromEntries(keys.map((k,i)=>[k,args[i]])));}if(sql.includes('INSERT INTO suggestions')){const keys=['id','device_id','player','category','body','created'];suggestions.set(args[0],Object.fromEntries(keys.map((k,i)=>[k,args[i]])));}if(sql.includes('DELETE FROM films'))films.delete(args[0]);return {meta:{changes:1}};}};}};return {DB,films,suggestions};}
test('shared film APIs allow public reads and require staff for publishing/removal, with idempotent saves',async()=>{const {DB,films}=database();for(const path of ['films','films/delete'])await assert.rejects(communityApi(request(path,clip),path,player,DB),(e:any)=>e.status===403);for(let i=0;i<2;i++){const r=await communityApi(request('films',clip),'films',staff,DB);assert.equal((await r!.json()).clip.provider,'drive');}assert.equal(films.size,1);await assert.rejects(communityApi(request('films',{...clip,title:'Changed'}),'films',staff,DB),(e:any)=>e.status===409);await assert.rejects(communityApi(request('films',{...clip,id:'duplicate'}),'films',staff,DB),(e:any)=>e.status===409);const read=await portableApi(request('films'),{DB,identity:async()=>player});assert.equal(read.status,200);assert.equal((await read.json()).clips.length,1);await communityApi(request('films/delete',{id:clip.id}),'films/delete',staff,DB);assert.equal(films.size,0);});
test('film links and shelves reject hostile URLs, folders, invalid categories and oversized text',()=>{assert.equal(videoLink(clip.url).embed,'https://drive.google.com/file/d/abcdefghijklm/preview');assert.equal(videoLink('https://drive.google.com/open?id=abcdefghijklm').provider,'drive');for(const b of [{...clip,url:'https://drive.google.com.evil.test/file/d/abcdefghijklm/view'},{...clip,url:'https://drive.google.com/drive/folders/abcdefghijklm'},{...clip,category:'Untrusted Shelf'},{...clip,cue:'a'.repeat(501)},{...clip,title:'a'.repeat(151)},{...clip,id:'../bad'}])assert.throws(()=>validateFilm(b),ApiError);});
test('youth suggestions require a signed device and roster player, cap submissions, and keep retry IDs stable',async()=>{const {DB,suggestions}=database(),body={id:'idea-1',player:'A',category:'Skill',body:'Left hand finishes'};await communityApi(request('suggestions',body),'suggestions',player,DB);await communityApi(request('suggestions',body),'suggestions',player,DB);assert.equal(suggestions.size,1);await assert.rejects(communityApi(request('suggestions',{...body,body:'Different'}),'suggestions',player,DB),(e:any)=>e.status===409);await assert.rejects(communityApi(request('suggestions',{...body,id:'unknown',player:'Unknown'}),'suggestions',player,DB),ApiError);const unsigned=new Request('https://swish.example/api/suggestions',{method:'POST',body:JSON.stringify(body)});await assert.rejects(communityApi(unsigned,'suggestions',player,DB),(e:any)=>e.status===409);for(let i=2;i<=5;i++)await communityApi(request('suggestions',{...body,id:'idea-'+i}),'suggestions',player,DB);await assert.rejects(communityApi(request('suggestions',{...body,id:'idea-6'}),'suggestions',player,DB),(e:any)=>e.status===429);const list=await portableApi(request('suggestions'),{DB,identity:async()=>player});assert.equal(list.status,200);const v=await list.json();assert.equal(v.suggestions.length,5);assert(!JSON.stringify(v).includes('device_id'));for(const value of [{...body,category:'Other'},{...body,body:' '},{...body,body:'a'.repeat(501)}])assert.throws(()=>validateSuggestion(value),ApiError);});
test('missing database cannot acknowledge a published clip or youth suggestion',async()=>{for(const path of ['films','suggestions']){const result=await portableApi(request(path,{...clip,player:'A',body:'Help'}),{DB:null,identity:async()=>staff});assert.equal(result.status,503);}const r=await portableApi(new Request('https://swish.example/api/films',{method:'DELETE',headers:{origin:'https://swish.example'}}),{DB:null});assert.equal(r.status,405);});
