import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
function setup(){const c:any=vm.createContext({console});for(const f of ['shots','model','development','stats-scope'])vm.runInContext(readFileSync('public/hub/'+f+'.js','utf8'),c);return c;}
function fixture(){const raw:any={Player_Roster:[{A:'Player Name',E:'SWISH Divisions'},{A:'Player A',D:'Active',E:'["U21"]'},{A:'Player B',D:'Active'},{A:'No Games',D:'Active'}],Player_Data:[{C:'Player Name',D:'Date',E:'Opponent',AO:'SWISH Division',AQ:'SWISH Game ID'}],Games:[{E:'Opponent',L:'SWISH Division',N:'SWISH Game ID'},{}],Shot_Data:[{E:'Player',F:'Zone',G:'Result',S:'SWISH Division',U:'SWISH Game ID'}]};
 for(let i=1;i<=12;i++){const year=i<=2?2024:i<=6?2025:2026,date=`${year}-01-${String(i).padStart(2,'0')}`,serial=Date.parse(date)/86400000+25569,id=`${serial}_${i}`,division=i<=2?'U18':i<=6?'U21':"Men's Open";const players=i<=8?['Player A','Player B']:['Player B'];raw.Games.push({A:id,B:i,C:serial,E:'Rivals '+i,G:players.length*i,H:i-1,L:division,N:id});for(const name of players)raw.Player_Data.push({C:name,D:serial,E:'Rivals '+i,I:i,J:2,K:1,L:1,M:0,O:1,V:1,W:2,AQ:id});raw.Shot_Data.push({A:id+'_1',B:serial,C:'Rivals '+i,D:1,E:players[0],F:'Mid-Range - Left',G:'Make',U:id});}
 raw.Player_Data.push({C:'Player A',D:0,E:'Unknown',I:99,V:8});raw.Player_Data.push({C:'Historical Only',D:Date.parse('2024-01-01')/86400000+25569,E:'Rivals 1',I:1});return raw;
}
const state=(mode='career',years:any=null,divisions:any=null)=>({mode,years,divisions});
test('selected calendar years combine correctly; undated stats stay career-only and unlisted players remain selectable',()=>{const c=setup(),raw=fixture(),before=JSON.stringify(raw),full=c.Swish.build(raw),career=c.SwishScope.apply(full,state()),selected=c.SwishScope.apply(full,state('seasons',['2024','2026']));assert.equal(career.players.find((p:any)=>p.name==='Player A').gp,9);assert.equal(selected.players.find((p:any)=>p.name==='Player A').gp,4);assert.equal(selected.games.length,8);assert.equal(selected.raw.Shot_Data.length,9);assert.equal(selected.players.find((p:any)=>p.name==='Player A').totals.pts,18);const only2026=c.SwishScope.apply(full,state('seasons',['2026']));assert.equal(only2026.players.find((p:any)=>p.name==='Historical Only').gp,0);assert.equal(only2026.players.find((p:any)=>p.name==='No Games').avg.pts,null);assert.equal(JSON.stringify(raw),before);});
test('empty year or division selections produce a real empty state, rather than reverting to all data',()=>{const c=setup(),full=c.Swish.build(fixture());for(const s of [state('seasons',[]),state('career',null,[]),state('seasons',['2023'])]){const m=c.SwishScope.apply(full,s);assert.equal(m.games.length,0);assert.equal(m.rows.length,0);assert(m.players.every((p:any)=>p.gp===0&&p.avg.pts===null));assert.equal(m.raw.Shot_Data.length,1);}});
test('last five distinguishes player appearances from team matches, preserves matching shots and omits undated records',()=>{const c=setup(),full=c.Swish.build(fixture()),m=c.SwishScope.apply(full,state('last5'));assert.equal(m.games.length,5);assert.equal(m.players.find((p:any)=>p.name==='Player A').gp,5);assert.equal(m.players.find((p:any)=>p.name==='Player A').totals.pts,30);assert.equal(m.teamPlayers.find((p:any)=>p.name==='Player A').gp,1);assert.equal(m.teamPlayers.find((p:any)=>p.name==='Player A').totals.pts,8);assert.equal(m.players.find((p:any)=>p.name==='Player A').shots.length,5);assert(m.players.every((p:any)=>p.rows.every((r:any)=>r.date)));assert.equal(m.rows.length,6);});
test('year and division filters use historical game divisions, never current roster membership',()=>{const c=setup(),full=c.Swish.build(fixture()),m=c.SwishScope.apply(full,state('seasons',['2024','2025'],['U18','U21']));assert.equal(m.games.length,6);assert.equal(m.players.find((p:any)=>p.name==='Player A').gp,6);const groups=c.SwishScope.summaries(m,'Player A');assert.equal(groups.length,2);assert.equal(groups[0].division,'U18');assert.equal(groups[0].avg.pts,1.5);assert.equal(groups[1].division,'U21');assert.equal(groups[1].avg.pts,4.5);const mens=c.SwishScope.apply(full,state('career',null,["Men's Open"]));assert.equal(mens.players.find((p:any)=>p.name==='Player A').gp,2);assert.equal(mens.games.length,6);});
test('team season summaries average complete game totals, use official points and keep missing statistics unrecorded',()=>{const c=setup(),raw=fixture();raw.Player_Data.find((r:any)=>r.C==='Player B'&&r.E==='Rivals 1').J=undefined;const full=c.Swish.build(raw),m=c.SwishScope.apply(full,state('seasons',['2024'])),g=c.SwishScope.summaries(m)[0];assert.equal(g.gp,2);assert.equal(g.avg.pts,3);assert.equal(g.totals.pts,6);assert.equal(g.counts.reb,1);assert.equal(g.avg.reb,4);assert.equal(g.fg,.5);});
test('paired shooting percentages exclude unpaired makes and keep missing inputs out of eFG and TS',()=>{const c=setup(),p=c.Swish.build(fixture()).players.find((p:any)=>p.name==='Player A');assert.equal(p.fg,.5);assert.equal(p.efg,null);assert.equal(p.ts,null);});
test('same-day last-five selection uses game number; unique game windows do not count duplicate rows as additional appearances',()=>{const c=setup(),raw=fixture();for(let i=1;i<=6;i++){const serial=46000,id=`${serial}_${i}`;raw.Games.push({A:id,C:serial,E:'Same-Day '+i,G:0,H:0,N:id});raw.Player_Data.push({C:'Player B',D:serial,E:'Same-Day '+i,I:i,AQ:id});}const full=c.Swish.build(raw),keys=c.SwishScope.recentKeys(full.rows.filter((r:any)=>r.name==='Player B'&&r.rawDate===46000));assert.equal(keys.size,5);assert(!keys.has('id:46000_1'));assert(keys.has('id:46000_6'));});
test('year filters for community records use season labels, dates and timestamps without guessing a division',()=>{const c=setup(),s=state('seasons',['2024','2025']);assert(c.SwishScope.recordMatches({season:'2024/25',awarded:'2026-01-01'},s));assert(c.SwishScope.recordMatches({created:'2025-10-09T12:00:00Z'},s));assert(!c.SwishScope.recordMatches({date:'2026-01-01'},s));assert(!c.SwishScope.recordMatches({season:'Unknown'},s));assert(c.SwishScope.recordMatches({season:'Unknown'},state()));});

test('cross-year award labels and Singapore note timestamps match the correct year',()=>{const c=setup();assert(c.SwishScope.recordMatches({season:'2024/25'},state('seasons',['2025'])));assert(c.SwishScope.recordMatches({created:'2025-12-31T16:30:00Z'},state('seasons',['2026'])));assert(!c.SwishScope.recordMatches({created:'2025-12-31T16:30:00Z'},state('seasons',['2025'])));});

test('Selected Years with all years selected still excludes undated records',()=>{const c=setup(),full=c.Swish.build(fixture()),m=c.SwishScope.apply(full,state('seasons',null));assert.equal(m.players.find((p:any)=>p.name==='Player A').gp,8);assert.equal(m.players.find((p:any)=>p.name==='Player A').totals.pts,36);});
