import { database } from './database';
export type Identity={id:string;email:string;role:'player'|'coach'|'volunteer';player:string|null;admin:boolean};
export class ApiError extends Error{constructor(message:string,public status=400){super(message)}}
export const reply=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export function authConfig(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new ApiError('Sign-in is not configured yet.',503);return {url,key}}
export async function authRequest(path:string,body?:unknown,token?:string){const {url,key}=authConfig();return fetch(`${url}/auth/v1/${path}`,{method:body===undefined?'GET':'POST',headers:{apikey:key,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store',signal:AbortSignal.timeout(12000)})}
export function cookies(request:Request){return Object.fromEntries((request.headers.get('cookie')||'').split(';').map(c=>{const i=c.indexOf('=');return [c.slice(0,i).trim(),c.slice(i+1)]}))}
export function setSession(response:Response,session:any,request:Request){const secure=new URL(request.url).protocol==='https:'?'; Secure':'';for(const [name,value,age] of [['swish_access',session.access_token,3600],['swish_refresh',session.refresh_token,2592000]] as const)response.headers.append('Set-Cookie',`${name}=${value||''}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${value?age:0}${secure}`);return response}
export function sameOrigin(request:Request){if(request.method==='GET')return;const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)throw new ApiError('Open this form from SWISH.',403)}
export async function identity(request:Request,DB=database(),fetchUser=(token:string)=>authRequest('user',undefined,token)):Promise<Identity>{const token=cookies(request).swish_access;if(!token)throw new ApiError('Sign in to SWISH.',401);const r=await fetchUser(token);if(!r.ok)throw new ApiError('Your session expired. Sign in again.',401);const u=await r.json();if(!u.id||!u.email||!u.email_confirmed_at)throw new ApiError('Confirm your email before signing in.',401);const email=u.email.toLowerCase();const admin=(process.env.SWISH_ADMIN_EMAILS||'').split(',').map(e=>e.trim().toLowerCase()).filter(Boolean).includes(email);await DB.prepare('INSERT INTO user_roles (id,email,role,player) VALUES (?,?,?,NULL) ON CONFLICT(id) DO UPDATE SET email=excluded.email').bind(u.id,email,admin?'coach':'player').run();const role=await DB.prepare('SELECT role,player FROM user_roles WHERE id=?').bind(u.id).first();return {id:u.id,email,role:admin?'coach':role?.role||'player',player:role?.player||null,admin};}
export function requireStaff(user:Identity){if(!['coach','volunteer'].includes(user.role))throw new ApiError('This feature is for coaches and volunteers.',403)}
export function requireAdmin(user:Identity){if(!user.admin)throw new ApiError('Only the club administrator can change account access.',403)}
