import { createHmac,createHash,randomBytes,timingSafeEqual } from 'node:crypto';
export type Identity={id:string;email:string;role:'player'|'coach'|'volunteer';player:string|null;admin:boolean};
export class ApiError extends Error{constructor(message:string,public status=400){super(message)}}
export const reply=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export function cookies(request:Request){return Object.fromEntries((request.headers.get('cookie')||'').split(';').map(c=>{const i=c.indexOf('=');return [c.slice(0,i).trim(),c.slice(i+1)]}))}
export function sameOrigin(request:Request){if(request.method==='GET')return;if(request.headers.get('origin')!==new URL(request.url).origin)throw new ApiError('Open this form from SWISH.',403)}
function secret(){const s=process.env.STAFF_SESSION_SECRET;if(!s||s.length<32)throw new ApiError('Staff access needs its server session secret configured.',503);return s;}
const equal=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
function sign(value:string,staff=false){return createHmac('sha256',secret()+(staff?'|'+(process.env.STAFF_PIN||''):'')).update(value).digest('hex')}
export function staffToken(now=Date.now()){const body=`staff.${Math.floor(now/1000)+28800}.${randomBytes(12).toString('hex')}`;return body+'.'+sign(body,true)}
export function validStaff(token:string,now=Date.now()){if(!token||token.split('.').length!==4)return false;try{const [role,expires,nonce,signature]=token.split('.');return role==='staff'&&/^\d+$/.test(expires)&&+expires>now/1000&&+expires<=now/1000+28801&&/^[a-f0-9]{24}$/.test(nonce)&&equal(signature||'',sign(`${role}.${expires}.${nonce}`,true));}catch{return false}}
export async function identity(request:Request):Promise<Identity>{const staff=validStaff(cookies(request).swish_staff||'');return {id:staff?'shared-staff':'player',email:staff?'SWISH staff':'Player view',role:staff?'coach':'player',player:null,admin:staff}}
export function requireStaff(user:Identity){if(!['coach','volunteer'].includes(user.role))throw new ApiError('Enter the staff PIN to use this tool.',403)}
export function cookie(response:Response,name:string,value:string,request:Request,age=28800){response.headers.append('Set-Cookie',`${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${value?age:0}${new URL(request.url).protocol==='https:'?'; Secure':''}`);return response}
export function device(request:Request){const token=cookies(request).swish_device||'',parts=token.split('.');if(parts.length===2&&/^[a-f0-9]{32}$/.test(parts[0]))try{if(equal(parts[1],sign(parts[0])))return {id:createHash('sha256').update(parts[0]).digest('hex'),token,new:false}}catch{}const id=randomBytes(16).toString('hex');return {id:createHash('sha256').update(id).digest('hex'),token:id+'.'+sign(id),new:true}}
const attempts=new Map<string,{count:number;reset:number}>();
export async function unlockPin(request:Request,DB?:any){const pin=process.env.STAFF_PIN;if(!pin)throw new ApiError('Set STAFF_PIN in Vercel first.',503);const body=await request.json();const bucket=createHash('sha256').update((request.headers.get('x-real-ip')||request.headers.get('x-forwarded-for')?.split(',')[0]||'local').trim()).digest('hex'),now=Date.now();let hits=0;
if(DB){const r=await DB.prepare('INSERT INTO pin_attempts (id,attempts,reset_at) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET attempts=CASE WHEN pin_attempts.reset_at < ? THEN 1 ELSE pin_attempts.attempts+1 END,reset_at=CASE WHEN pin_attempts.reset_at < ? THEN excluded.reset_at ELSE pin_attempts.reset_at END RETURNING attempts').bind(bucket,now+900000,now,now).first();hits=r.attempts;}else{let r=attempts.get(bucket);if(!r||r.reset<now){r={count:0,reset:now+900000};attempts.set(bucket,r)}hits=++r.count;if(attempts.size>5000)for(const [k,v] of attempts)if(v.reset<now)attempts.delete(k);}
if(hits>5)throw new ApiError('Too many PIN attempts. Wait 15 minutes before trying again.',429);if(typeof body.pin!=='string'||!equal(createHash('sha256').update(body.pin).digest('hex'),createHash('sha256').update(pin).digest('hex')))throw new ApiError('That staff PIN is incorrect.',401);if(DB)await DB.prepare('DELETE FROM pin_attempts WHERE id=?').bind(bucket).run();else attempts.delete(bucket);return cookie(reply({ok:true}), 'swish_staff',staffToken(),request)}
