import {ApiError,reply,device,requireStaff,type Identity} from './auth';
import {getLiveSheet} from './google-sheet';
const str=(v:unknown,max=200,required=true)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw new ApiError('Check the required text fields.');return v.trim()};
const date=(v:unknown)=>{const s=str(v,10);if(!/^20\d{2}-\d{2}-\d{2}$/.test(s)||isNaN(Date.parse(s))||new Date(s+'T00:00:00Z').toISOString().slice(0,10)!==s)throw new ApiError('Choose a valid date.');return s};
const int=(v:unknown,max=10000)=>{if(!Number.isInteger(v)||Number(v)<0||Number(v)>max)throw new ApiError('Enter a valid non-negative whole number.');return Number(v)};
export function names(v:unknown){const list=str(v,3000).split(/[,\n]+/).map(s=>s.trim()).filter(Boolean);const unique=[...new Map(list.map(s=>[s.toLowerCase(),s])).values()];if(unique.length>100||unique.some(s=>s.length>100))throw new ApiError('Enter up to 100 player names, separated by commas or new lines.');return unique;}
export function videoLink(input:unknown){let u:URL;try{u=new URL(str(input,1200))}catch{throw new ApiError('Paste a valid https video link.')}if(u.protocol!=='https:')throw new ApiError('Use an https YouTube, Instagram or Google Drive link.');const host=u.hostname.toLowerCase().replace(/^www\./,'');let id:string|undefined|null;if(['youtube.com','m.youtube.com','youtube-nocookie.com'].includes(host)){id=u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed|live)\/([^/]+)/)?.[1]}else if(host==='youtu.be')id=u.pathname.split('/')[1];if(id&&/^[A-Za-z0-9_-]{11}$/.test(id))return {provider:'youtube',url:`https://www.youtube.com/watch?v=${id}`,embed:`https://www.youtube-nocookie.com/embed/${id}`};if(host==='instagram.com'){const m=u.pathname.match(/^\/(p|reel|tv)\/([A-Za-z0-9_-]+)\/?$/);if(m)return {provider:'instagram',url:`https://www.instagram.com/${m[1]}/${m[2]}/`,embed:`https://www.instagram.com/${m[1]}/${m[2]}/embed/`}}if(host==='drive.google.com'){id=u.pathname.match(/^\/file\/d\/([A-Za-z0-9_-]+)(?:\/|$)/)?.[1]||(['open','uc'].includes(u.pathname.slice(1))?u.searchParams.get('id'):null);if(id&&/^[A-Za-z0-9_-]{10,200}$/.test(id))return {provider:'drive',url:`https://drive.google.com/file/d/${id}/view`,embed:`https://drive.google.com/file/d/${id}/preview`};}throw new ApiError('Paste a YouTube video, Instagram post/Reel, or Google Drive video file link. Folder links are not supported.');}
export function validateStint(b:any){const players=b.players;if(!Array.isArray(players)||players.length!==5||players.some(p=>typeof p!=='string'||!p.trim()||p.length>100)||new Set(players).size!==5)throw new ApiError('Choose five different players.');const period=int(b.period,10),start=int(b.startClock,3600),end=int(b.endClock,3600);if(period<1||start<=end)throw new ApiError('End clock must be lower than start clock in the same period.');const startFor=int(b.startFor,1000),startAgainst=int(b.startAgainst,1000),endFor=int(b.endFor,1000),endAgainst=int(b.endAgainst,1000);if(endFor<startFor||endAgainst<startAgainst)throw new ApiError('End scores must be no lower than start scores.');const possFor=b.possFor===null||b.possFor===''||b.possFor===undefined?null:int(b.possFor,300),possAgainst=b.possAgainst===null||b.possAgainst===''||b.possAgainst===undefined?null:int(b.possAgainst,300);if((possFor===null)!==(possAgainst===null)||possFor===0||possAgainst===0)throw new ApiError('For efficiency per 100 possessions, enter both possession counts greater than zero, or leave both blank.');return {id:str(b.id,60),game:str(b.game,200),players,period,start,end,startFor,startAgainst,endFor,endAgainst,possFor,possAgainst,note:str(b.note||'',500,false)};}
export function validateFilm(b:any){const link=videoLink(b.url),category=str(b.category,40),id=str(b.id,80);if(!/^[A-Za-z0-9_-]{1,80}$/.test(id))throw new ApiError('Check the clip ID.');if(!['Skills Library','5 On 5 Plays','3 On 3 Plays','Game Footage'].includes(category))throw new ApiError('Choose a Film Room shelf.');return {id,title:str(b.title,150),url:link.url,provider:link.provider,category,cue:str(b.cue||'',500,false)};}
export function validateSuggestion(b:any){const id=str(b.id,80),player=str(b.player,100),category=str(b.category,20),body=str(b.body,500);if(!/^[A-Za-z0-9_-]{1,80}$/.test(id))throw new ApiError('Check the suggestion ID.');if(!['Drill','Skill','Play','Film'].includes(category))throw new ApiError('Choose Drill, Skill, Play Or Film.');return {id,player,category,body};}
export async function communityApi(request:Request,path:string,user:Identity,DB:any){const get=request.method==='GET';
if(path==='community'&&get){if(!DB)return reply({films:[],awards:[],predictions:[],stints:[],backendReady:false});const r=await DB.batch([DB.prepare('SELECT * FROM awards ORDER BY awarded DESC'),DB.prepare('SELECT id,player,date,opponent,metrics,created FROM predictions ORDER BY date DESC'),...(user.role==='player'?[]:[DB.prepare('SELECT * FROM lineup_stints ORDER BY created DESC')])]);return reply({awards:r[0].results,predictions:r[1].results.map((p:any)=>({...p,metrics:JSON.parse(p.metrics)})),stints:(r[2]?.results||[]).map((s:any)=>({...s,players:JSON.parse(s.players)})),backendReady:true})}
if(!['community','predictions','award-votes','suggestions'].includes(path)&&!(path==='films'&&get))requireStaff(user);
if(path==='films'&&get)return reply({clips:DB?(await DB.prepare('SELECT * FROM films ORDER BY created DESC LIMIT 500').all()).results:[],ready:!!DB});
if(path==='suggestions'&&get)return reply({suggestions:DB?(await DB.prepare('SELECT id,player,category,body,created FROM suggestions ORDER BY created DESC LIMIT 100').all()).results:[]});
if(!DB)throw new ApiError('Connect the Supabase database to enable shared saves. See the Setup tab.',503);
const b=get?{}:await request.json(),now=new Date().toISOString();
if(path==='films'&&!get){const clip=validateFilm(b),existing=await DB.prepare('SELECT * FROM films WHERE id=?').bind(clip.id).first();if(existing){if(Object.entries(clip).some(([k,v])=>existing[k]!==v))throw new ApiError('This clip ID was already saved with different details.',409);return reply({ok:true,clip:existing});}const duplicate=await DB.prepare('SELECT id FROM films WHERE url=?').bind(clip.url).first();if(duplicate)throw new ApiError('This clip is already published. Choose it from the Film Room.',409);const count=await DB.prepare('SELECT COUNT(*)::int AS count FROM films').first();if(count.count>=500)throw new ApiError('The shared Film Room is full. Remove a clip before adding another.',409);await DB.prepare('INSERT INTO films (id,title,url,provider,category,cue,created) VALUES (?,?,?,?,?,?,?)').bind(clip.id,clip.title,clip.url,clip.provider,clip.category,clip.cue,now).run();return reply({ok:true,clip:{...clip,created:now}},201);}
if(path==='films/delete'&&!get){await DB.prepare('DELETE FROM films WHERE id=?').bind(str(b.id,80)).run();return reply({ok:true});}
if(path==='suggestions'&&!get){const suggestion=validateSuggestion(b),d=device(request);if(d.new)throw new ApiError('Refresh the page before sharing a suggestion.',409);const existing=await DB.prepare('SELECT * FROM suggestions WHERE id=?').bind(suggestion.id).first();if(existing){if(existing.device_id!==d.id||Object.entries(suggestion).some(([k,v])=>existing[k]!==v))throw new ApiError('This suggestion ID was already saved with different details.',409);return reply({ok:true});}const since=new Date(Date.now()-86400000).toISOString(),count=await DB.prepare('SELECT COUNT(*)::int AS count FROM suggestions WHERE device_id=? AND created>=?').bind(d.id,since).first();if(count.count>=5)throw new ApiError('You Can Share Five Suggestions Per Day. Try Again Tomorrow.',429);const live=await getLiveSheet(DB);if(live.stale)throw new ApiError('Wait For A Fresh Roster Sync Before Sharing.',503);if(!(live.raw as any).Player_Roster.slice(1).some((r:any)=>r.A===suggestion.player))throw new ApiError('Choose A Player From The Roster.');await DB.prepare('INSERT INTO suggestions (id,device_id,player,category,body,created) VALUES (?,?,?,?,?,?)').bind(suggestion.id,d.id,suggestion.player,suggestion.category,suggestion.body,now).run();return reply({ok:true},201);}
if(path==='award-votes'&&get){const d=device(request);const [counts,own]=await Promise.all([DB.prepare('SELECT player,title,season,COUNT(*)::int AS votes FROM award_votes GROUP BY player,title,season ORDER BY season DESC,player,title').all(),DB.prepare('SELECT player,title,season,reason FROM award_votes WHERE device_id=? ORDER BY season DESC,title').bind(d.id).all()]);return reply({counts:counts.results,own:own.results});}
if(path==='award-votes'&&!get){const player=str(b.player,100),title=str(b.title,100),season=str(b.season,30),reason=str(b.reason||'',600,false);if(!['Hustle Player of the Year','Most Improved Player','Teammate of the Year','Volunteer Champion','Defensive Player of the Year'].includes(title))throw new ApiError('Choose an end-of-year award.');if(!/^20\d{2}(?:[ /-]20\d{2})?$/.test(season))throw new ApiError('Use a season such as 2026 or 2026-2027.');const d=device(request);if(d.new)throw new ApiError('Refresh the page before voting.',409);const live=await getLiveSheet(DB);if(live.stale)throw new ApiError('Wait for a fresh roster sync before voting.',503);if(!(live.raw as any).Player_Roster.slice(1).some((r:any)=>r.A===player))throw new ApiError('Choose a player from the roster.');await DB.prepare('INSERT INTO award_votes (id,device_id,player,title,season,reason,created,updated) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(device_id,title,season) DO UPDATE SET player=excluded.player,reason=excluded.reason,updated=excluded.updated').bind(crypto.randomUUID(),d.id,player,title,season,reason,now,now).run();return reply({ok:true});}

if(path==='predictions'&&!get){const player=str(b.player,100),when=date(b.date),opponent=str(b.opponent,150),metrics=b.metrics;if(!metrics||typeof metrics!=='object'||Array.isArray(metrics)||Object.keys(metrics).some(k=>!['pts','reb','ast','stl','blk','to'].includes(k))||Object.keys(metrics).length===0)throw new ApiError('Enter at least one forecast.');for(const v of Object.values(metrics))int(v,200);const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'});if(when<today)throw new ApiError('Forecasts must be entered before the game.');const live=await getLiveSheet(DB,fetch,true);if(live.stale)throw new ApiError('Wait for a fresh Sheet sync before saving a prediction.',503);const {raw}=live,serial=Date.parse(when)/86400000+25569;if(!(raw as any).Player_Roster.slice(1).some((r:any)=>r.A===player))throw new ApiError('Choose a player from the roster.');if((raw as any).Player_Data.slice(1).some((r:any)=>r.C===player&&Number(r.D)===serial&&String(r.E||'').trim().toLowerCase()===opponent.toLowerCase()))throw new ApiError('This game already has a box score. Forecasts are locked.');const d=device(request);if(d.new)throw new ApiError('Refresh the page before saving your forecast.',409);await DB.prepare('INSERT INTO predictions (id,device_id,player,date,opponent,metrics,created) VALUES (?,?,?,?,?,?,?) ON CONFLICT(device_id,player,date,opponent) DO UPDATE SET metrics=excluded.metrics').bind(crypto.randomUUID(),d.id,player,when,opponent.toLowerCase(),JSON.stringify(metrics),now).run();return reply({ok:true})}
if(path==='notes'&&get)return reply((await DB.prepare('SELECT * FROM observations ORDER BY created DESC').all()).results);
if(path==='notes'&&!get){await DB.prepare('INSERT INTO observations (id,player,category,body,author,created) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),str(b.player,100),str(b.category,100),str(b.body,1200),user.email,now).run();return reply({ok:true});}
if(path==='check-ins'&&get)return reply((await DB.prepare('SELECT * FROM check_ins ORDER BY date DESC,created DESC').all()).results.map((s:any)=>({...s,names:JSON.parse(s.names)})));
if(path==='check-ins'&&!get){const id=b.id?str(b.id,60):crypto.randomUUID(),revision=b.id?int(b.revision,100000):0,list=names(b.names);if(!['Volunteering session','Match'].includes(b.kind))throw new ApiError('Choose a volunteering session or match.');if(b.id){const r=await DB.prepare('UPDATE check_ins SET title=?,date=?,kind=?,names=?,revision=revision+1 WHERE id=? AND revision=?').bind(str(b.title,150),date(b.date),b.kind,JSON.stringify(list),id,revision).run();if(!r.meta.changes)throw new ApiError('This check-in changed. Refresh before editing.',409)}else await DB.prepare('INSERT INTO check_ins (id,title,date,kind,names,revision,created) VALUES (?,?,?,?,?,1,?)').bind(id,str(b.title,150),date(b.date),b.kind,JSON.stringify(list),now).run();return reply({ok:true,id})}
if(path==='awards'&&!get){const {raw}=await getLiveSheet(DB);if(!(raw as any).Player_Roster.slice(1).some((r:any)=>r.A===b.player))throw new ApiError('Choose a player from the roster.');await DB.prepare('INSERT INTO awards (id,player,title,season,event_key,reason,awarded) VALUES (?,?,?,?,?,?,?) ON CONFLICT(player,title,season,event_key) DO NOTHING').bind(crypto.randomUUID(),str(b.player,100),str(b.title,100),str(b.season,30),str(b.eventKey,200),str(b.reason||'',600,false),date(b.awarded)).run();return reply({ok:true})}
if(path==='awards/delete'&&!get){await DB.prepare('DELETE FROM awards WHERE id=?').bind(str(b.id,60)).run();return reply({ok:true})}
if(path==='lineup-stints'&&!get){const s=validateStint(b),clientDB=DB;const {raw}=await getLiveSheet(DB);if(!(raw as any).Games.slice(1).some((r:any)=>String(r.A||'')===s.game))throw new ApiError('Choose a game from the tracker.');if(s.players.some(p=>!(raw as any).Player_Roster.slice(1).some((r:any)=>r.A===p)))throw new ApiError('Choose players from the roster.');const existing=await DB.prepare('SELECT * FROM lineup_stints WHERE id=?').bind(s.id).first();if(existing){const same=existing.game_id===s.game&&JSON.stringify(JSON.parse(existing.players).slice().sort())===JSON.stringify(s.players.slice().sort())&&existing.period===s.period&&existing.start_clock===s.start&&existing.end_clock===s.end&&existing.start_for===s.startFor&&existing.start_against===s.startAgainst&&existing.end_for===s.endFor&&existing.end_against===s.endAgainst&&existing.poss_for===s.possFor&&existing.poss_against===s.possAgainst&&existing.note===s.note;if(!same)throw new ApiError('This stint was already saved with different values.',409);return reply({ok:true});}const overlap=await DB.prepare('SELECT id FROM lineup_stints WHERE game_id=? AND period=? AND start_clock > ? AND end_clock < ? AND id <> ?').bind(s.game,s.period,s.end,s.start,s.id).first();if(overlap)throw new ApiError('A saved stint already covers part of this time. Check the period and clocks.',409);await clientDB.prepare('INSERT INTO lineup_stints (id,game_id,players,period,start_clock,end_clock,start_for,start_against,end_for,end_against,poss_for,poss_against,note,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(s.id,s.game,JSON.stringify(s.players),s.period,s.start,s.end,s.startFor,s.startAgainst,s.endFor,s.endAgainst,s.possFor,s.possAgainst,s.note,now).run();return reply({ok:true})}
if(path==='lineup-stints/delete'&&!get){await DB.prepare('DELETE FROM lineup_stints WHERE id=?').bind(str(b.id,60)).run();return reply({ok:true})}
return null;
}
