export const GOOGLE_SHEET_ID=process.env.GOOGLE_SHEET_ID||'1Z3suEMnt_FnA0_umEG4E-Crxm52y0nmJSXyVCGi-AnI';
export const GOOGLE_SHEET_URL=`https://docs.google.com/spreadsheets/d/${GOOGLE_SHEET_ID}/edit`;
const CACHE_KEY='google-live';
type Table={cols:{id:string;label:string;type:string}[];rows:{c:({v:unknown;f?:string}|null)[]}[]};
function normalise(v:unknown,type:string){if(v===null||v===undefined)return null;if(type==='date'||type==='datetime'){const m=String(v).match(/^Date\((\d+),(\d+),(\d+)(?:,.*)?\)$/);if(!m)throw Error('A Google Sheet date could not be read.');return (Date.UTC(+m[1],+m[2],+m[3])/86400000)+25569;}return v;}
export function tableToRows(table:Table){if(!table||!Array.isArray(table.cols)||!Array.isArray(table.rows))throw Error('Google returned an unreadable worksheet.');if(table.rows.length>12000||table.cols.length>200)throw Error('This worksheet is too large to sync.');const header=Object.fromEntries(table.cols.map(c=>[c.id,c.label]));const rows=table.rows.map(r=>Object.fromEntries(table.cols.map((c,i)=>[c.id,normalise(r.c?.[i]?.v,c.type)]).filter(([,v])=>v!==null)));return [header,...rows.filter(r=>Object.keys(r).length)];}
export function decodeGoogleResponse(body:string){const start=body.indexOf('{'),end=body.lastIndexOf('}');if(start<0||end<start)throw Error('Google Sheet access is unavailable.');const result=JSON.parse(body.slice(start,end+1));if(result.status!=='ok')throw Error('Google could not read this worksheet. Keep the original tab names and viewer access.');return tableToRows(result.table);}
async function signature(raw:unknown){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(raw)));return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('');}
export async function loadGoogleTabs(fetcher:typeof fetch=fetch){const tabs=['Player_Roster','Player_Data','Games'];const results=await Promise.all(tabs.map(async tab=>{const url=`https://docs.google.com/spreadsheets/d/${GOOGLE_SHEET_ID}/gviz/tq?tqx=out:json&headers=1&sheet=${tab}&range=A1:AW12000`;const r=await fetcher(url,{signal:AbortSignal.timeout(20000),cache:'no-store'});if(!r.ok)throw Error('Google Sheet is unavailable. Check that the source sheet allows Anyone with the link to view.');return [tab,decodeGoogleResponse(await r.text())]}));return {...Object.fromEntries(results),Shot_Data:[]};}
export async function getLiveSheet(DB:any,fetcher:typeof fetch=fetch,force=false){let cache:any=null;try{if(DB)cache=await DB.prepare('SELECT raw,updated FROM dataset WHERE id=?').bind(CACHE_KEY).first();}catch(e){console.error('Sheet cache read failed',e)}const checkedAt=new Date().toISOString();const makeResult=async(raw:unknown,syncedAt:string,stale=false,error:string|null=null)=>({raw,name:'SWISH · Live Google Sheet',signature:await signature(raw),syncedAt,checkedAt,stale,error,sheetUrl:GOOGLE_SHEET_URL,refreshSeconds:60});if(cache&&!force&&Date.now()-Date.parse(cache.updated)<45000)return makeResult(JSON.parse(cache.raw),cache.updated);
 try{const raw=await loadGoogleTabs(fetcher),syncedAt=new Date().toISOString();if(DB)try{await DB.prepare('INSERT INTO dataset (id,raw,name,blob_key,revision,author,updated) VALUES (?,?,?,?,1,?,?) ON CONFLICT(id) DO UPDATE SET raw=excluded.raw,revision=dataset.revision+1,updated=excluded.updated').bind(CACHE_KEY,JSON.stringify(raw),'SWISH · Live Google Sheet','','Google Sheet sync',syncedAt).run();}catch(e){console.error('Sheet cache save failed',e)}return makeResult(raw,syncedAt);}catch(e){const error=e instanceof Error?e.message:'Could not connect to Google Sheets.';if(cache)return makeResult(JSON.parse(cache.raw),cache.updated,true,error);throw Error(error);}}
