import { ApiError,identity,requireStaff,requireAdmin,sameOrigin,reply,authRequest,cookies,setSession,type Identity } from './auth';
import {database,workbookStorage} from './database';
import {swishApi} from './swish-api';
import {getLiveSheet} from './google-sheet';
import {validateGame,writeGame} from './game-entry';
export function playerStats(raw:Record<string,any[]>){const allowed={Player_Roster:['A','B','C','D'],Player_Data:['A','B','C','D','E','F','I','J','K','L','M','N','O','V','W','Z','AA','AB','AC','AD','AE','AF','AG','AH','AI'],Games:['A','C','D','E','F','G','H'],Shot_Data:[]};return Object.fromEntries(Object.entries(allowed).map(([tab,cols])=>[tab,(raw[tab]||[]).map(r=>Object.fromEntries(cols.filter(c=>r[c]!==undefined).map(c=>[c,r[c]])))]));}
export async function portableApi(request:Request,services:{DB?:any;identity?:typeof identity;live?:typeof getLiveSheet;write?:typeof writeGame}={}){try{sameOrigin(request);const path=new URL(request.url).pathname.replace(/^\/api\//,'');const method=request.method;
if(path.startsWith('auth/')){if(path==='auth/sign-out'&&method==='POST'){const token=cookies(request).swish_access;if(token)await authRequest('logout',{},token);return setSession(reply({ok:true}),{},request)}if(path==='auth/refresh'&&method==='POST'){const token=cookies(request).swish_refresh;if(!token)throw new ApiError('Sign in again.',401);const r=await authRequest('token?grant_type=refresh_token',{refresh_token:token});if(!r.ok)throw new ApiError('Sign in again.',401);return setSession(reply({ok:true}),await r.json(),request)}if(['auth/sign-in','auth/sign-up'].includes(path)&&method==='POST'){const b=await request.json();if(typeof b.email!=='string'||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email)||typeof b.password!=='string'||b.password.length<8||b.password.length>128)throw new ApiError('Enter your email and a password of at least 8 characters.');const r=await authRequest(path==='auth/sign-in'?'token?grant_type=password':'signup',{email:b.email.trim(),password:b.password});const session=await r.json();if(!r.ok)throw new ApiError(path==='auth/sign-in'?'Check your email, password and email confirmation.':'Account creation failed. Try signing in or contact your coach.',400);if(path==='auth/sign-up'&&!session.access_token)return reply({confirmEmail:true});return setSession(reply({ok:true}),session,request)}}
const DB=services.DB||database(),user=await (services.identity||identity)(request,DB);if(path==='auth/me'&&method==='GET')return reply(user);
if(path==='live-sheet'&&method==='GET'){const result=await (services.live||getLiveSheet)(DB,fetch,new URL(request.url).searchParams.get('refresh')==='now');return reply({...result,raw:playerStats(result.raw as any),sheetUrl:user.role==='player'?null:result.sheetUrl})}
if(path==='player-clubhouse'&&method==='GET'){if(!user.player)return reply({sessions:[],attendance:[],duties:[],quests:[],notes:[],dataset:null,unlinked:true});const q=await DB.prepare('SELECT id,player,title,target,due,status FROM quests WHERE player=? ORDER BY updated DESC').bind(user.player).all(),a=await DB.prepare('SELECT session_id,player,state FROM attendance WHERE player=?').bind(user.player).all(),s=await DB.prepare('SELECT id,status FROM sessions WHERE id IN (SELECT session_id FROM attendance WHERE player=?)').bind(user.player).all();return reply({sessions:s.results,attendance:a.results,duties:[],quests:q.results,notes:[],dataset:null})}
requireStaff(user);
if(path==='games'&&method==='POST'){const body=await request.json();return reply(await (services.write||writeGame)(validateGame(body),user.email),201)}
if(path==='accounts'&&method==='GET'){requireAdmin(user);const r=await DB.prepare('SELECT id,email,role,player FROM user_roles ORDER BY email').all();return reply(r.results)}
if(path==='accounts'&&method==='POST'){requireAdmin(user);const b=await request.json();if(typeof b.id!=='string'||! /^[0-9a-f-]{36}$/i.test(b.id)||!['player','coach','volunteer'].includes(b.role)||(b.player!==null&&(typeof b.player!=='string'||b.player.length>100)))throw new ApiError('Choose a valid account role and player.');if(b.player){const {raw}=await getLiveSheet(DB);if(!(raw as any).Player_Roster.slice(1).some((r:any)=>r.A===b.player))throw new ApiError('Choose a player from the roster.');}const r=await DB.prepare('UPDATE user_roles SET role=?,player=? WHERE id=?').bind(b.role,b.player,b.id).run();if(!r.meta.changes)throw new ApiError('Account not found.',404);return reply({ok:true})}
// Never trust incoming platform headers. Replace them only after verified authentication.
const headers=new Headers(request.headers);headers.set('oai-authenticated-user-id',user.id);headers.set('oai-authenticated-user-email',user.email);return swishApi(new Request(request,{headers}),{DB,BUCKET:['dataset','workbook'].includes(path)?workbookStorage():null});
}catch(e){if(e instanceof ApiError)return reply({error:e.message},e.status);console.error('SWISH request failed',e instanceof Error?e.message:'Unknown error');return reply({error:'The clubhouse could not complete this request. Your input is retained; try again.'},503)}}
