import { getLiveSheet } from './google-sheet';
export type Services={DB:any;BUCKET:any;fetcher?:typeof fetch};
class InputError extends Error {status:number;constructor(message:string,status=400){super(message);this.status=status}}
const text=(v:unknown,max=250,required=true)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw new InputError('Please check the required fields and text length.');return v.trim()};
const iso=(v:unknown)=>{const s=text(v,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||isNaN(Date.parse(s))||new Date(s+'T00:00:00Z').toISOString().slice(0,10)!==s)throw new InputError('Choose a valid date.');return s};
const option=(v:unknown,values:string[])=>{if(typeof v!=='string'||!values.includes(v))throw new InputError('Choose a valid option.');return v};
const integer=(v:unknown,min:number,max:number)=>{if(!Number.isInteger(v)||Number(v)<min||Number(v)>max)throw new InputError('Choose a valid whole number.');return Number(v)};
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function swishApi(request:Request,services:Services){
 const {DB,BUCKET}=services;const url=new URL(request.url);const path=url.pathname.replace(/^\/api\//,'');const method=request.method;
 try{
  if(path==='live-sheet'&&method==='GET'){try{return json(await getLiveSheet(DB,services.fetcher,url.searchParams.get('refresh')==='now'));}catch(e){return json({error:e instanceof Error?e.message:'Could not connect to Google Sheets.',stale:true},503);}}
  const user=request.headers.get('oai-authenticated-user-id');if(!user)return json({error:'Sign in to access the shared clubhouse.'},401);
  const author=request.headers.get('oai-authenticated-user-email')||user;
  if(method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==url.origin)return json({error:'This request must come from the clubhouse.'},403)}
  if(!DB)throw Error('Shared storage is unavailable.');
  if(path==='clubhouse'&&method==='GET'){const r=await DB.batch(['SELECT * FROM sessions ORDER BY date DESC,time DESC','SELECT * FROM attendance','SELECT * FROM duties','SELECT * FROM quests ORDER BY updated DESC','SELECT * FROM observations ORDER BY created DESC LIMIT 300','SELECT name,revision,updated FROM dataset WHERE id = ?'].map((s,i)=>i===5?DB.prepare(s).bind('current'):DB.prepare(s)));return json({sessions:r[0].results,attendance:r[1].results,duties:r[2].results,quests:r[3].results,notes:r[4].results,dataset:r[5].results[0]||null,user:author});}
  if(path==='dataset'&&method==='GET'){const row=await DB.prepare('SELECT raw,name,revision FROM dataset WHERE id = ?').bind('current').first();return json(row?{raw:JSON.parse(row.raw),name:row.name,revision:row.revision}:null);}
  if(path==='workbook'&&method==='GET'){const d=await DB.prepare('SELECT blob_key,name FROM dataset WHERE id = ?').bind('current').first();if(!d)return json({error:'No shared workbook uploaded yet.'},404);if(!BUCKET)throw Error('Workbook storage is unavailable.');const blob=await BUCKET.get(d.blob_key);if(!blob)return json({error:'The workbook file is unavailable.'},404);return new Response(blob.body,{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="${d.name.replace(/[^A-Za-z0-9_.-]/g,'_')}"`,'Cache-Control':'no-store'}});}
  if(path==='dataset'&&method==='POST'){
   if(!BUCKET)throw Error('Workbook storage is unavailable.');const form=await request.formData(),file=form.get('file'),rawString=form.get('raw');if(!(file instanceof File)||!file.name.toLowerCase().endsWith('.xlsx')||file.size>20*1024*1024||file.size===0)throw new InputError('Choose an .xlsx workbook smaller than 20 MB.');
   const raw=JSON.parse(text(rawString,1000000));if(!Array.isArray(raw.Player_Data)||!Array.isArray(raw.Player_Roster)||!Array.isArray(raw.Games)||!raw.Player_Data[0]?.C?.toLowerCase().includes('player')||!raw.Games[0]?.E?.toLowerCase().includes('opponent'))throw new InputError('The workbook columns do not match the SWISH tracker.');
   const rev=integer(Number(form.get('revision')),0,1000000),id=crypto.randomUUID(),key=`workbooks/${id}.xlsx`,now=new Date().toISOString();await BUCKET.put(key,await file.arrayBuffer());let result;
   try{if(rev===0)result=await DB.prepare('INSERT OR IGNORE INTO dataset (id,raw,name,blob_key,revision,author,updated) VALUES (?,?,?,?,1,?,?)').bind('current',JSON.stringify(raw),file.name,key,author,now).run();else result=await DB.prepare('UPDATE dataset SET raw=?,name=?,blob_key=?,revision=revision+1,author=?,updated=? WHERE id=? AND revision=?').bind(JSON.stringify(raw),file.name,key,author,now,'current',rev).run();}catch(e){await BUCKET.delete(key);throw e}
   if(!result.meta.changes){await BUCKET.delete(key);throw new InputError('Another staff member updated the workbook. Reload before uploading again.',409)}return json({revision:rev+1,name:file.name});
  }
  const payload:unknown=method==='GET'?{}:await request.json();if(typeof payload!=='object'||payload===null||Array.isArray(payload))throw new InputError('Send a valid form.');const body=payload as Record<string,unknown>;const now=new Date().toISOString();
  if(path==='sessions/edit'&&method==='POST'){const id=text(body.id,60),rev=integer(body.revision,1,1000000),title=text(body.title,120),date=iso(body.date),time=text(body.time,5);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw new InputError('Choose a valid time.');const r=await DB.prepare('UPDATE sessions SET title=?,date=?,time=?,venue=?,lead=?,focus=?,duration=?,plan=?,revision=revision+1,author=?,updated=? WHERE id=? AND revision=?').bind(title,date,time,text(body.venue,150),text(body.lead,100),text(body.focus,200),integer(body.duration,10,240),text(body.plan,8000),author,now,id,rev).run();if(!r.meta.changes)throw new InputError('This session changed. Refresh before editing again.',409);return json({ok:true});}
  if(path==='sessions'&&method==='POST'){const title=text(body.title,120),date=iso(body.date),time=text(body.time,5);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw new InputError('Choose a valid time.');const id=crypto.randomUUID();await DB.prepare('INSERT INTO sessions (id,title,date,time,venue,lead,focus,duration,plan,status,revision,author,updated) VALUES (?,?,?,?,?,?,?,?,?,\'planned\',1,?,?)').bind(id,title,date,time,text(body.venue,150),text(body.lead,100),text(body.focus,200),integer(body.duration,10,240),text(body.plan,8000),author,now).run();return json({id},201);}
  if(path==='sessions/status'&&method==='POST'){const status=option(body.status,['planned','complete','cancelled']),rev=integer(body.revision,1,1000000),id=text(body.id,60);const r=await DB.prepare('UPDATE sessions SET status=?,revision=revision+1,updated=?,author=? WHERE id=? AND revision=?').bind(status,now,author,id,rev).run();if(!r.meta.changes)throw new InputError('This session changed. Refresh and try again.',409);return json({ok:true});}
  if(path==='attendance'&&method==='POST'){const sessionId=text(body.sessionId,60),player=text(body.player,100),state=option(body.state,['present','absent','excused','unmarked']);if(!await DB.prepare('SELECT id FROM sessions WHERE id=?').bind(sessionId).first())throw new InputError('Session not found.',404);if(state==='unmarked')await DB.prepare('DELETE FROM attendance WHERE session_id=? AND player=?').bind(sessionId,player).run();else await DB.prepare('INSERT INTO attendance (session_id,player,state,author,updated) VALUES (?,?,?,?,?) ON CONFLICT(session_id,player) DO UPDATE SET state=excluded.state,author=excluded.author,updated=excluded.updated').bind(sessionId,player,state,author,now).run();return json({ok:true});}
  if(path==='duties'&&method==='POST'){const id=crypto.randomUUID(),sessionId=text(body.sessionId,60),task=text(body.task,200),volunteer=text(body.volunteer,100);if(!await DB.prepare('SELECT id FROM sessions WHERE id=?').bind(sessionId).first())throw new InputError('Session not found.',404);await DB.prepare('INSERT INTO duties (id,session_id,task,volunteer,done,author) VALUES (?,?,?,?,0,?)').bind(id,sessionId,task,volunteer,author).run();return json({id},201);}
  if(path==='duties/status'&&method==='POST'){const done=integer(body.done,0,1),id=text(body.id,60);const r=await DB.prepare('UPDATE duties SET done=?,author=? WHERE id=?').bind(done,author,id).run();if(!r.meta.changes)throw new InputError('Duty not found.',404);return json({ok:true});}
  if(path==='quests'&&method==='POST'){const id=crypto.randomUUID(),player=text(body.player,100),title=text(body.title,120),target=text(body.target,300),due=iso(body.due);await DB.prepare('INSERT INTO quests (id,player,title,target,due,status,evidence,author,updated) VALUES (?,?,?,?,?,\'active\',\'\',?,?)').bind(id,player,title,target,due,author,now).run();return json({id},201);}
  if(path==='quests/status'&&method==='POST'){const id=text(body.id,60),status=option(body.status,['active','complete']),evidence=text(body.evidence,600,status==='complete');const r=await DB.prepare('UPDATE quests SET status=?,evidence=?,author=?,updated=? WHERE id=?').bind(status,evidence,author,now,id).run();if(!r.meta.changes)throw new InputError('Quest not found.',404);return json({ok:true});}
  if(path==='notes'&&method==='POST'){const id=crypto.randomUUID(),player=text(body.player,100),category=option(body.category,['Strength','Next step','Session reflection']),note=text(body.body,1600);await DB.prepare('INSERT INTO observations (id,player,category,body,author,created) VALUES (?,?,?,?,?,?)').bind(id,player,category,note,author,now).run();return json({id},201);}
  return json({error:'Not found.'},404);
 }catch(e){if(e instanceof InputError)return json({error:e.message},e.status);if(e instanceof SyntaxError)return json({error:'The request contains unreadable data.'},400);console.error('Clubhouse storage request failed',e);return json({error:'The shared clubhouse could not save or load this change. Your input is still here; try again.'},503)}
}
